apiVersion: apps/v1
kind: Deployment
metadata:
  name: muscle-map-2d
  labels:
    app: muscle-map-2d
spec:
  replicas: 1
  selector:
    matchLabels:
      app: muscle-map-2d
  template:
    metadata:
      labels:
        app: muscle-map-2d
    spec:
      containers:
      - name: muscle-map-2d
        image: asia-northeast1-docker.pkg.dev/docker-repo-490401/muscle-repo/my-app:v2-amd64
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        env:
        - name: PORT
          value: "3000"