apiVersion: v1
kind: Service
metadata:
  name: muscle-map-2d-lb
  labels:
    app: muscle-map-2d
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  selector:
    app: muscle-map-2d